name: Deploy app

on:
  push:
    branches:
      - main
    paths:
      - src/app/**
      - .github/workflows/app.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          lfs: true
          submodules: true
          clean: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: yarn
          cache-dependency-path: src/app/yarn.lock

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
        working-directory: src/app

      - name: Build project
        run: |
          yarn build
        working-directory: src/app
        env:
          VITE_API_ROOT: https://app-projectestimate-api-dev.azurewebsites.net/api

      - name: Package artifact
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: app
          path: src/app/dist

  deploy:
    needs: build
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: app

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: app-projectestimate-ui-dev
          package: app
